name: MiltonWorkshop
favicon: null
layout_spectrum: 0.48097
typography_spectrum: 0.41478
title: Milton Workshop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffa927'
    - '#f2f2f2'
    - '#1f1e1d'
    - '#8f6322'
    - '#888887'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
