name: MiltonWorkshop
favicon: null
layout_spectrum: 0.56662
typography_spectrum: 0.0940365050919354
title: Milton Workshop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc580c'
    - '#fdca49'
    - '#ffa927'
    - '#f8872e'
    - '#f2f2f2'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
