name: MiltonWorkshop
favicon: null
layout_spectrum: 0.74971
typography_spectrum: 0.39373
title: Milton Workshop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#ffa927'
    - '#fcb64d'
    - '#f6d6a5'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
